<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Productos;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // <-- Agrega esta línea

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
{
    // Obtener todas las categorías por nombre
    $categorias = Categoria::all()->keyBy('nombre'); // crea un mapa con el nombre como clave
    $medicamentos = [
        ['Alka -D', 'Tableta'],
        ['Alka-Seltzer', 'Tableta'],
        ['Sal Andrews', 'Sobre'],
        ['Pepto Bismol', 'Frasco'],
        ['Pepto Bismol', 'Tableta masticable'],
        ['Enterogermina', 'Vial'],
        ['Pediaflora', 'Sobre'],
        ['Ruigel Plus', 'Frasco'],
        ['Neutrox', 'Frasco'],
        ['Sucralfato (sucrasyl)', 'Sobre'],
        ['Suero Oral', 'Sobre'],
        ['Suero Oral (electroral)', 'Frasco'],
        ['Suero Oral (hidravida)', 'Frasco'],
        ['Nifuroxazida', 'Tableta'],
        ['Esomeprazol', 'Tableta'],
        ['Lanzoprazol Adulto', 'Sobre'],
        ['Lanzoprazol Niños', 'Sobre'],
        ['Virogrip Dia', 'Tableta'],
        ['Virogrip Noche', 'Tableta'],
        ['Virogrip Dia', 'Sobre'],
        ['Virogrip Noche', 'Sobre'],
        ['Ambroxol', 'Jarabe'],
        ['Menaxol', 'Vial'],
        ['Menaxol', 'Sobre'],
        ['Ambiare', 'Jarabe'],
        ['Hedera Helix', 'Jarabe'],
        ['Vaporub', 'Ungüento'],
        ['Vaporub', 'Inhalador'],
        ['Virogrip', 'Inyectable'],
        ['Emagrip', 'Inyectable'],
        ['Neumonil', 'Inyectable'],
        ['Aspirina', 'Tableta'],
        ['Aspirina forte', 'Tableta'],
        ['Acetaminofen MK', 'Tableta'],
        ['Acetaminofen', 'Jarabe'],
        ['Acetaminofen Selectpharma', 'Jarabe'],
        ['Metamizol', 'Tableta'],
        ['Metamizol', 'Suspensión'],
        ['Diclofenaco', 'Tableta'],
        ['Diclofenaco', 'Suspensión'],
        ['Ibuprofeno', 'Tableta'],
        ['Ibuprofeno', 'Tableta 600mg'],
        ['Ibuprofeno', 'Tableta 800mg'],
        ['Ibuprofeno', 'Suspensión'],
        ['Ibuprofeno Selectpharma', 'Suspensión'],


       ['Dexketoprofeno', 'Tableta'],
        ['Dolo-Neurobion', 'Tableta'],
        ['Dolo-Neurobion', 'Inyectable'],
        ['Vitaflenaco', 'Tableta'],
        ['Metronidazol Flagelos', 'Tableta'],
        ['Metronidazol Metriquin', 'Tableta'],
        ['Metronidazol Flagelos', 'Suspensión'],
        ['metronizadol Selectpharma', 'Suspensión'],
        ['Metronidazol', 'Inyectable'],
        ['Albendazol MK', 'Tableta'],
        ['Albendazol MK', 'Suspensión'],
     //   ['Albendazol Selectpharma', 'Tableta'],
        ['Fluconazol Selectpharma', 'Tableta'],
        ['Fluconazol Farmandina', 'Tableta'],
        ['Tinidazol Selectharma', 'Tableta'],
        ['Clotrimazol Selectpharma', 'Crema Vaginal'],
        ['Clotrimazol Pharmadel', 'Óvulos'],
        ['Clotrimazol Selectpharma', 'Crema tópica'],
        ['Nitazoxanida Nitax', 'Tableta'],
        ['Nitazoxanida Nitax', 'Suspensión'],
        ['Sertal Compuesto', 'Tableta'],
        ['Sertal Compuesto', 'Gotas'],
        ['Loratadina Farmandina', 'Suspensión'],
        ['Loratadina Selectpharma', 'Suspensión'],
        ['Loratadina Selectpharma', 'Tableta'],
        ['Maleato de Clorfeniramina', 'Tableta'],
        ['Maleato de Clorfeniramina', 'Suspensión'],
        ['Calamina Lancasco', 'Loción'],
        ['Amoxicilina caplin', 'Tabletas'],
        ['Amoxicilina Lancasco', 'Suspensión'],
        ['Amoxicilina mas acido clavulánico Claxil', 'Suspensión'],
        ['Amoxicilina mas acido clavulánico Claxil', 'Tabletas'],
        ['Amoxicilina mas acido clavulánico Coac', 'Tabletas'],
        ['Ciprofloxacina Soriflox', 'Tabletas'],
        ['Ciprofloxacina Brociflox', 'Tabletas'],
        ['Ciprofloxacina', 'Inyectable'],
        ['Ceftriaxona', 'Vial'],
        ['Cefixima Katius', 'Suspensión'],
        ['Cefixima Katius', 'Tableta'],
        ['Trimetroprim', 'Suspensión'],
        ['Trimetroprim Bonatril forte', 'Tabletas'],
        ['Dicloxacilina', 'Tabletas'],
        ['Aciclovir acivirex', 'Crema'],
        ['Aciclovir Infasa', 'Tableta'],
        ['Cofal', 'Crema'],
        ['Vitaflenaco', 'Gel'],
        ['Ontol Gel', 'Gel'],
        ['Canesten', 'Crema'],
        ['Canesten 6 aplicadores', 'Crema Vaginal'],
        ['Caneten 3 aplicadores', 'Crema Vaginal'],
        ['Canesten V 6', 'Óvulos'],
        ['Canesten 3', 'Óvulos'],
        ['Canesten 1', 'Óvulos'],
        ['Clotriplex', 'Lata'],
        ['Clotriplex', 'Crema'],
        ['Pasta Lassar', 'Crema'],
        ['Vitamina C', 'Masticable'],
        ['Vitamina C', 'Efervescente'],
        ['Zinc', 'Tabletas'],
        ['Zinc', 'Suspensión'],
        ['Sukrol', 'Tabletas'],
        ['Centrum', 'Tabletas'],
        ['Centrum Silver', 'Tabletas'],
        ['Centrum Mujer', 'Tabletas'],
        ['Centrum Hombre', 'Tabletas'],
        ['Menopace', 'Tabletas'],
        ['Mineravit Complex', 'Suspensión'],
        ['Dayamineral', 'Jarabe'],
        ['Dayamineral', 'Tabletas'],
        ['Forza Plus', 'Jarabe'],
        ['Forza Plus', 'Tabletas'],
    // ['Toallas Sanitarias Kotex Manzanilla', 'null'],
     //   ['Toallas Sanitarias Kotex Nocturnas', 'null'],
      //  ['Toallas Sanitarias Saba', ''],
       // ['Toallas Sanitarias Saba nocturna', 'null'],
       // ['Toallas Humedas Huggies', 'null'],
       // ['Pasta Dental Colgate total 12', 'null'],
       // ['Pasta Dental Colgate triple accion', 'null'],
       // ['Cepillo  Dental triple accion', 'null'],
       // ['Cepillo Dental niños', 'null'],
       // ['Hilo Dental  Normal', 'null'],
       // ['Hilo Dental Menta', 'null'],
        //['Enjuague Bucal Listerine', 'null'],
        //['Enjuague Bucal Colgate', 'null'],
        //['Condones Vive Amor', 'null'],
        //['Condones Vive tradicional', 'null'],
        //['Enalapril 20mg', 'null'],
        //['Metformina 850mg', 'null'],
       // ['Jeringas 10 cc', 'null'],
       // ['Jeringas 5 cc', 'null'],
      //  ['Jeringas 3cc', 'null'],
     //   ['Jeringas 1cc', 'null'],
      //  ['Venoclisis', 'null'],
      //  ['angiocath  20', 'null'],
      //  ['Angiocath 22', 'null'],
      //  ['Angiocath 18', 'null'],
      //  ['Micropore Blanco', 'null'],
      //  ['Micropore Piel', 'null'],
      //  ['Algodón', 'null'],
      //  ['Alcohol', 'null'],
      //  ['Agua oxigenada', 'null'],
      //  ['Sellos de Heparina', 'null'],
    ];
    foreach ($medicamentos as $index => [$nombre, $categoriaNombre]) {
        $categoria_id = $categorias[$categoriaNombre]->id ?? null;

        Productos::create([
            'id' => $index + 1,
            'codigo' => 'MED' . str_pad($index + 1, 4, '0', STR_PAD_LEFT),
            'nombre' => $nombre,
            'descripcion' => $categoriaNombre, // Puedes usar la presentación si no tienes otra descripción
            'imagen' => 'default.png',
            'categoria_id' => $categoria_id, // se asigna correctamente
        ]);
    }
    }
}